FROM node:18-alpine 
WORKDIR /app
COPY . . 

RUN npm install snyk -g 
RUN npm install snyk-to-html -g 
 
ARG SNYK_AUTH_TOKEN
ENV SNYK_AUTH_TOKEN=$OUTPUT_FILENAME

RUN snyk auth $SNYK_AUTH_TOKEN && snyk test --json | snyk-to-html -o $OUTPUT_FILENAME.html || true