apiVersion: apps/v1
kind: Deployment
metadata:
  name: sneaker-ecommerce-backend-deployment
  namespace: sneaker-ecommerce-ns
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sneaker-ecommerce-backend
  template:
    metadata:
      labels:
        app: sneaker-ecommerce-backend
    spec:
      containers:
        - name: sneaker-ecommerce-backend
          image: anphuc2370/online-shop-backend:release-v1.0.0_6e5eb834
          ports:
            - containerPort: 5214
          volumeMounts:
            - name: sneaker-ecommerce-backend-volume
              mountPath: /run/appsettings.json
              subPath: appsettings.json
          envFrom:
            - secretRef:
                name: sneaker-ecommerce-secrets-connect-database
          env:
            - name: ConnectionStrings__UserAppCon
              value: "Server=$(MSSQL_HOST),$(MSSQL_PORT);Database=$(MSSQL_NAME);User Id=$(MSSQL_USER);Password=$(MSSQL_PASSWORD)"
          resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi"
      volumes:
        - name: sneaker-ecommerce-backend-volume
          configMap:
            name: sneaker-ecommerce-backend-appsettings-configmap
            defaultMode: 420

---
apiVersion: v1
kind: Service
metadata:
  name: sneaker-ecommerce-backend-sv
  namespace: sneaker-ecommerce-ns
spec:
  type: ClusterIP
  selector:
    app: sneaker-ecommerce-backend
  ports:
    - port: 80
      targetPort: 5214

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sneaker-ecommerce-backend-appsettings-configmap
  namespace: sneaker-ecommerce-ns
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "UserAppCon": ""
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "Jwt": {
        "Secret": "your_secret_key_here"
      },
      "AllowedHosts": "*"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: sneaker-ecommerce-secrets-connect-database
  namespace: sneaker-ecommerce-ns
type: Opaque
stringData:
  MSSQL_HOST: "192.168.254.112"
  MSSQL_PORT: "1433"
  MSSQL_NAME: "OnlineShopDB"
  MSSQL_USER: "sa"
  MSSQL_PASSWORD: "Anphuc@1231"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sneaker-ecommerce-backend-ingress
  namespace: sneaker-ecommerce-ns
spec:
  ingressClassName: nginx
  rules:
    - host: api-sneaker-shop.anphuc.tech
      http:
        paths:
          - backend:
              service:
                name: sneaker-ecommerce-backend-sv
                port:
                  number: 80
            path: /
            pathType: Prefix

--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sneaker-ecommerce-backend-autoscaling
  namespace: sneaker-ecommerce-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sneaker-ecommerce-backend-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
